/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-05 at 09:21:58 UTC 
 * Modify at your own risk.
 */

package ch.technotracks.gpsdataendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gpsdataendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean championship;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Championship> championships;

  static {
    // hack to force ProGuard to consider Championship used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Championship.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String eMail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String firstname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lastname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String phoneNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean takePartChampionship;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Track> tracks;

  static {
    // hack to force ProGuard to consider Track used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Track.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getChampionship() {
    return championship;
  }

  /**
   * @param championship championship or {@code null} for none
   */
  public User setChampionship(java.lang.Boolean championship) {
    this.championship = championship;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Championship> getChampionships() {
    return championships;
  }

  /**
   * @param championships championships or {@code null} for none
   */
  public User setChampionships(java.util.List<Championship> championships) {
    this.championships = championships;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEMail() {
    return eMail;
  }

  /**
   * @param eMail eMail or {@code null} for none
   */
  public User setEMail(java.lang.String eMail) {
    this.eMail = eMail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFirstname() {
    return firstname;
  }

  /**
   * @param firstname firstname or {@code null} for none
   */
  public User setFirstname(java.lang.String firstname) {
    this.firstname = firstname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public User setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastname() {
    return lastname;
  }

  /**
   * @param lastname lastname or {@code null} for none
   */
  public User setLastname(java.lang.String lastname) {
    this.lastname = lastname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public User setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * @param phoneNumber phoneNumber or {@code null} for none
   */
  public User setPhoneNumber(java.lang.String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getTakePartChampionship() {
    return takePartChampionship;
  }

  /**
   * @param takePartChampionship takePartChampionship or {@code null} for none
   */
  public User setTakePartChampionship(java.lang.Boolean takePartChampionship) {
    this.takePartChampionship = takePartChampionship;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Track> getTracks() {
    return tracks;
  }

  /**
   * @param tracks tracks or {@code null} for none
   */
  public User setTracks(java.util.List<Track> tracks) {
    this.tracks = tracks;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
