/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-03 at 13:17:58 UTC 
 * Modify at your own risk.
 */

package ch.technotracks.championshipendpoint;

/**
 * Service definition for Championshipendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ChampionshipendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Championshipendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the championshipendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "championshipendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Championshipendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Championshipendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getChampionship".
   *
   * This request holds the parameters needed by the championshipendpoint server.  After setting any
   * optional parameters, call the {@link GetChampionship#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetChampionship getChampionship(java.lang.Long id) throws java.io.IOException {
    GetChampionship result = new GetChampionship(id);
    initialize(result);
    return result;
  }

  public class GetChampionship extends ChampionshipendpointRequest<ch.technotracks.championshipendpoint.model.Championship> {

    private static final String REST_PATH = "championship/{id}";

    /**
     * Create a request for the method "getChampionship".
     *
     * This request holds the parameters needed by the the championshipendpoint server.  After setting
     * any optional parameters, call the {@link GetChampionship#execute()} method to invoke the remote
     * operation. <p> {@link GetChampionship#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetChampionship(java.lang.Long id) {
      super(Championshipendpoint.this, "GET", REST_PATH, null, ch.technotracks.championshipendpoint.model.Championship.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetChampionship setAlt(java.lang.String alt) {
      return (GetChampionship) super.setAlt(alt);
    }

    @Override
    public GetChampionship setFields(java.lang.String fields) {
      return (GetChampionship) super.setFields(fields);
    }

    @Override
    public GetChampionship setKey(java.lang.String key) {
      return (GetChampionship) super.setKey(key);
    }

    @Override
    public GetChampionship setOauthToken(java.lang.String oauthToken) {
      return (GetChampionship) super.setOauthToken(oauthToken);
    }

    @Override
    public GetChampionship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetChampionship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetChampionship setQuotaUser(java.lang.String quotaUser) {
      return (GetChampionship) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetChampionship setUserIp(java.lang.String userIp) {
      return (GetChampionship) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetChampionship setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetChampionship set(String parameterName, Object value) {
      return (GetChampionship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertChampionship".
   *
   * This request holds the parameters needed by the championshipendpoint server.  After setting any
   * optional parameters, call the {@link InsertChampionship#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ch.technotracks.championshipendpoint.model.Championship}
   * @return the request
   */
  public InsertChampionship insertChampionship(ch.technotracks.championshipendpoint.model.Championship content) throws java.io.IOException {
    InsertChampionship result = new InsertChampionship(content);
    initialize(result);
    return result;
  }

  public class InsertChampionship extends ChampionshipendpointRequest<ch.technotracks.championshipendpoint.model.Championship> {

    private static final String REST_PATH = "championship";

    /**
     * Create a request for the method "insertChampionship".
     *
     * This request holds the parameters needed by the the championshipendpoint server.  After setting
     * any optional parameters, call the {@link InsertChampionship#execute()} method to invoke the
     * remote operation. <p> {@link InsertChampionship#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link ch.technotracks.championshipendpoint.model.Championship}
     * @since 1.13
     */
    protected InsertChampionship(ch.technotracks.championshipendpoint.model.Championship content) {
      super(Championshipendpoint.this, "POST", REST_PATH, content, ch.technotracks.championshipendpoint.model.Championship.class);
    }

    @Override
    public InsertChampionship setAlt(java.lang.String alt) {
      return (InsertChampionship) super.setAlt(alt);
    }

    @Override
    public InsertChampionship setFields(java.lang.String fields) {
      return (InsertChampionship) super.setFields(fields);
    }

    @Override
    public InsertChampionship setKey(java.lang.String key) {
      return (InsertChampionship) super.setKey(key);
    }

    @Override
    public InsertChampionship setOauthToken(java.lang.String oauthToken) {
      return (InsertChampionship) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertChampionship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertChampionship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertChampionship setQuotaUser(java.lang.String quotaUser) {
      return (InsertChampionship) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertChampionship setUserIp(java.lang.String userIp) {
      return (InsertChampionship) super.setUserIp(userIp);
    }

    @Override
    public InsertChampionship set(String parameterName, Object value) {
      return (InsertChampionship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listChampionship".
   *
   * This request holds the parameters needed by the championshipendpoint server.  After setting any
   * optional parameters, call the {@link ListChampionship#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListChampionship listChampionship() throws java.io.IOException {
    ListChampionship result = new ListChampionship();
    initialize(result);
    return result;
  }

  public class ListChampionship extends ChampionshipendpointRequest<ch.technotracks.championshipendpoint.model.CollectionResponseChampionship> {

    private static final String REST_PATH = "championship";

    /**
     * Create a request for the method "listChampionship".
     *
     * This request holds the parameters needed by the the championshipendpoint server.  After setting
     * any optional parameters, call the {@link ListChampionship#execute()} method to invoke the
     * remote operation. <p> {@link ListChampionship#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListChampionship() {
      super(Championshipendpoint.this, "GET", REST_PATH, null, ch.technotracks.championshipendpoint.model.CollectionResponseChampionship.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListChampionship setAlt(java.lang.String alt) {
      return (ListChampionship) super.setAlt(alt);
    }

    @Override
    public ListChampionship setFields(java.lang.String fields) {
      return (ListChampionship) super.setFields(fields);
    }

    @Override
    public ListChampionship setKey(java.lang.String key) {
      return (ListChampionship) super.setKey(key);
    }

    @Override
    public ListChampionship setOauthToken(java.lang.String oauthToken) {
      return (ListChampionship) super.setOauthToken(oauthToken);
    }

    @Override
    public ListChampionship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListChampionship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListChampionship setQuotaUser(java.lang.String quotaUser) {
      return (ListChampionship) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListChampionship setUserIp(java.lang.String userIp) {
      return (ListChampionship) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListChampionship setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListChampionship setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListChampionship set(String parameterName, Object value) {
      return (ListChampionship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeChampionship".
   *
   * This request holds the parameters needed by the championshipendpoint server.  After setting any
   * optional parameters, call the {@link RemoveChampionship#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveChampionship removeChampionship(java.lang.Long id) throws java.io.IOException {
    RemoveChampionship result = new RemoveChampionship(id);
    initialize(result);
    return result;
  }

  public class RemoveChampionship extends ChampionshipendpointRequest<Void> {

    private static final String REST_PATH = "championship/{id}";

    /**
     * Create a request for the method "removeChampionship".
     *
     * This request holds the parameters needed by the the championshipendpoint server.  After setting
     * any optional parameters, call the {@link RemoveChampionship#execute()} method to invoke the
     * remote operation. <p> {@link RemoveChampionship#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveChampionship(java.lang.Long id) {
      super(Championshipendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveChampionship setAlt(java.lang.String alt) {
      return (RemoveChampionship) super.setAlt(alt);
    }

    @Override
    public RemoveChampionship setFields(java.lang.String fields) {
      return (RemoveChampionship) super.setFields(fields);
    }

    @Override
    public RemoveChampionship setKey(java.lang.String key) {
      return (RemoveChampionship) super.setKey(key);
    }

    @Override
    public RemoveChampionship setOauthToken(java.lang.String oauthToken) {
      return (RemoveChampionship) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveChampionship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveChampionship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveChampionship setQuotaUser(java.lang.String quotaUser) {
      return (RemoveChampionship) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveChampionship setUserIp(java.lang.String userIp) {
      return (RemoveChampionship) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveChampionship setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveChampionship set(String parameterName, Object value) {
      return (RemoveChampionship) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateChampionship".
   *
   * This request holds the parameters needed by the championshipendpoint server.  After setting any
   * optional parameters, call the {@link UpdateChampionship#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ch.technotracks.championshipendpoint.model.Championship}
   * @return the request
   */
  public UpdateChampionship updateChampionship(ch.technotracks.championshipendpoint.model.Championship content) throws java.io.IOException {
    UpdateChampionship result = new UpdateChampionship(content);
    initialize(result);
    return result;
  }

  public class UpdateChampionship extends ChampionshipendpointRequest<ch.technotracks.championshipendpoint.model.Championship> {

    private static final String REST_PATH = "championship";

    /**
     * Create a request for the method "updateChampionship".
     *
     * This request holds the parameters needed by the the championshipendpoint server.  After setting
     * any optional parameters, call the {@link UpdateChampionship#execute()} method to invoke the
     * remote operation. <p> {@link UpdateChampionship#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link ch.technotracks.championshipendpoint.model.Championship}
     * @since 1.13
     */
    protected UpdateChampionship(ch.technotracks.championshipendpoint.model.Championship content) {
      super(Championshipendpoint.this, "PUT", REST_PATH, content, ch.technotracks.championshipendpoint.model.Championship.class);
    }

    @Override
    public UpdateChampionship setAlt(java.lang.String alt) {
      return (UpdateChampionship) super.setAlt(alt);
    }

    @Override
    public UpdateChampionship setFields(java.lang.String fields) {
      return (UpdateChampionship) super.setFields(fields);
    }

    @Override
    public UpdateChampionship setKey(java.lang.String key) {
      return (UpdateChampionship) super.setKey(key);
    }

    @Override
    public UpdateChampionship setOauthToken(java.lang.String oauthToken) {
      return (UpdateChampionship) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateChampionship setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateChampionship) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateChampionship setQuotaUser(java.lang.String quotaUser) {
      return (UpdateChampionship) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateChampionship setUserIp(java.lang.String userIp) {
      return (UpdateChampionship) super.setUserIp(userIp);
    }

    @Override
    public UpdateChampionship set(String parameterName, Object value) {
      return (UpdateChampionship) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Championshipendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Championshipendpoint}. */
    @Override
    public Championshipendpoint build() {
      return new Championshipendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ChampionshipendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setChampionshipendpointRequestInitializer(
        ChampionshipendpointRequestInitializer championshipendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(championshipendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
