/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-05 at 09:21:29 UTC 
 * Modify at your own risk.
 */

package ch.technotracks.championshipendpoint.model;

/**
 * Model definition for Track.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the championshipendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Track extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime create;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GPSData> gps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean sync;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private User user;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Vehicle vehicle;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreate() {
    return create;
  }

  /**
   * @param create create or {@code null} for none
   */
  public Track setCreate(com.google.api.client.util.DateTime create) {
    this.create = create;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<GPSData> getGps() {
    return gps;
  }

  /**
   * @param gps gps or {@code null} for none
   */
  public Track setGps(java.util.List<GPSData> gps) {
    this.gps = gps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Track setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Track setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSync() {
    return sync;
  }

  /**
   * @param sync sync or {@code null} for none
   */
  public Track setSync(java.lang.Boolean sync) {
    this.sync = sync;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public User getUser() {
    return user;
  }

  /**
   * @param user user or {@code null} for none
   */
  public Track setUser(User user) {
    this.user = user;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Vehicle getVehicle() {
    return vehicle;
  }

  /**
   * @param vehicle vehicle or {@code null} for none
   */
  public Track setVehicle(Vehicle vehicle) {
    this.vehicle = vehicle;
    return this;
  }

  @Override
  public Track set(String fieldName, Object value) {
    return (Track) super.set(fieldName, value);
  }

  @Override
  public Track clone() {
    return (Track) super.clone();
  }

}
