/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-03 at 13:18:12 UTC 
 * Modify at your own risk.
 */

package ch.technotracks.gpsdataendpoint;

/**
 * Service definition for Gpsdataendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GpsdataendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Gpsdataendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the gpsdataendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "gpsdataendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Gpsdataendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Gpsdataendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getGPSData".
   *
   * This request holds the parameters needed by the gpsdataendpoint server.  After setting any
   * optional parameters, call the {@link GetGPSData#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetGPSData getGPSData(java.lang.Long id) throws java.io.IOException {
    GetGPSData result = new GetGPSData(id);
    initialize(result);
    return result;
  }

  public class GetGPSData extends GpsdataendpointRequest<ch.technotracks.gpsdataendpoint.model.GPSData> {

    private static final String REST_PATH = "gpsdata/{id}";

    /**
     * Create a request for the method "getGPSData".
     *
     * This request holds the parameters needed by the the gpsdataendpoint server.  After setting any
     * optional parameters, call the {@link GetGPSData#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetGPSData#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetGPSData(java.lang.Long id) {
      super(Gpsdataendpoint.this, "GET", REST_PATH, null, ch.technotracks.gpsdataendpoint.model.GPSData.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGPSData setAlt(java.lang.String alt) {
      return (GetGPSData) super.setAlt(alt);
    }

    @Override
    public GetGPSData setFields(java.lang.String fields) {
      return (GetGPSData) super.setFields(fields);
    }

    @Override
    public GetGPSData setKey(java.lang.String key) {
      return (GetGPSData) super.setKey(key);
    }

    @Override
    public GetGPSData setOauthToken(java.lang.String oauthToken) {
      return (GetGPSData) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGPSData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGPSData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGPSData setQuotaUser(java.lang.String quotaUser) {
      return (GetGPSData) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGPSData setUserIp(java.lang.String userIp) {
      return (GetGPSData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetGPSData setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetGPSData set(String parameterName, Object value) {
      return (GetGPSData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertGPSData".
   *
   * This request holds the parameters needed by the gpsdataendpoint server.  After setting any
   * optional parameters, call the {@link InsertGPSData#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ch.technotracks.gpsdataendpoint.model.GPSData}
   * @return the request
   */
  public InsertGPSData insertGPSData(ch.technotracks.gpsdataendpoint.model.GPSData content) throws java.io.IOException {
    InsertGPSData result = new InsertGPSData(content);
    initialize(result);
    return result;
  }

  public class InsertGPSData extends GpsdataendpointRequest<ch.technotracks.gpsdataendpoint.model.GPSData> {

    private static final String REST_PATH = "gpsdata";

    /**
     * Create a request for the method "insertGPSData".
     *
     * This request holds the parameters needed by the the gpsdataendpoint server.  After setting any
     * optional parameters, call the {@link InsertGPSData#execute()} method to invoke the remote
     * operation. <p> {@link InsertGPSData#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link ch.technotracks.gpsdataendpoint.model.GPSData}
     * @since 1.13
     */
    protected InsertGPSData(ch.technotracks.gpsdataendpoint.model.GPSData content) {
      super(Gpsdataendpoint.this, "POST", REST_PATH, content, ch.technotracks.gpsdataendpoint.model.GPSData.class);
    }

    @Override
    public InsertGPSData setAlt(java.lang.String alt) {
      return (InsertGPSData) super.setAlt(alt);
    }

    @Override
    public InsertGPSData setFields(java.lang.String fields) {
      return (InsertGPSData) super.setFields(fields);
    }

    @Override
    public InsertGPSData setKey(java.lang.String key) {
      return (InsertGPSData) super.setKey(key);
    }

    @Override
    public InsertGPSData setOauthToken(java.lang.String oauthToken) {
      return (InsertGPSData) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertGPSData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertGPSData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertGPSData setQuotaUser(java.lang.String quotaUser) {
      return (InsertGPSData) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertGPSData setUserIp(java.lang.String userIp) {
      return (InsertGPSData) super.setUserIp(userIp);
    }

    @Override
    public InsertGPSData set(String parameterName, Object value) {
      return (InsertGPSData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listGPSData".
   *
   * This request holds the parameters needed by the gpsdataendpoint server.  After setting any
   * optional parameters, call the {@link ListGPSData#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListGPSData listGPSData() throws java.io.IOException {
    ListGPSData result = new ListGPSData();
    initialize(result);
    return result;
  }

  public class ListGPSData extends GpsdataendpointRequest<ch.technotracks.gpsdataendpoint.model.CollectionResponseGPSData> {

    private static final String REST_PATH = "gpsdata";

    /**
     * Create a request for the method "listGPSData".
     *
     * This request holds the parameters needed by the the gpsdataendpoint server.  After setting any
     * optional parameters, call the {@link ListGPSData#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListGPSData#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListGPSData() {
      super(Gpsdataendpoint.this, "GET", REST_PATH, null, ch.technotracks.gpsdataendpoint.model.CollectionResponseGPSData.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListGPSData setAlt(java.lang.String alt) {
      return (ListGPSData) super.setAlt(alt);
    }

    @Override
    public ListGPSData setFields(java.lang.String fields) {
      return (ListGPSData) super.setFields(fields);
    }

    @Override
    public ListGPSData setKey(java.lang.String key) {
      return (ListGPSData) super.setKey(key);
    }

    @Override
    public ListGPSData setOauthToken(java.lang.String oauthToken) {
      return (ListGPSData) super.setOauthToken(oauthToken);
    }

    @Override
    public ListGPSData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListGPSData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListGPSData setQuotaUser(java.lang.String quotaUser) {
      return (ListGPSData) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListGPSData setUserIp(java.lang.String userIp) {
      return (ListGPSData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListGPSData setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListGPSData setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListGPSData set(String parameterName, Object value) {
      return (ListGPSData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeGPSData".
   *
   * This request holds the parameters needed by the gpsdataendpoint server.  After setting any
   * optional parameters, call the {@link RemoveGPSData#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveGPSData removeGPSData(java.lang.Long id) throws java.io.IOException {
    RemoveGPSData result = new RemoveGPSData(id);
    initialize(result);
    return result;
  }

  public class RemoveGPSData extends GpsdataendpointRequest<Void> {

    private static final String REST_PATH = "gpsdata/{id}";

    /**
     * Create a request for the method "removeGPSData".
     *
     * This request holds the parameters needed by the the gpsdataendpoint server.  After setting any
     * optional parameters, call the {@link RemoveGPSData#execute()} method to invoke the remote
     * operation. <p> {@link RemoveGPSData#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveGPSData(java.lang.Long id) {
      super(Gpsdataendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveGPSData setAlt(java.lang.String alt) {
      return (RemoveGPSData) super.setAlt(alt);
    }

    @Override
    public RemoveGPSData setFields(java.lang.String fields) {
      return (RemoveGPSData) super.setFields(fields);
    }

    @Override
    public RemoveGPSData setKey(java.lang.String key) {
      return (RemoveGPSData) super.setKey(key);
    }

    @Override
    public RemoveGPSData setOauthToken(java.lang.String oauthToken) {
      return (RemoveGPSData) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveGPSData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveGPSData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveGPSData setQuotaUser(java.lang.String quotaUser) {
      return (RemoveGPSData) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveGPSData setUserIp(java.lang.String userIp) {
      return (RemoveGPSData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveGPSData setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveGPSData set(String parameterName, Object value) {
      return (RemoveGPSData) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateGPSData".
   *
   * This request holds the parameters needed by the gpsdataendpoint server.  After setting any
   * optional parameters, call the {@link UpdateGPSData#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ch.technotracks.gpsdataendpoint.model.GPSData}
   * @return the request
   */
  public UpdateGPSData updateGPSData(ch.technotracks.gpsdataendpoint.model.GPSData content) throws java.io.IOException {
    UpdateGPSData result = new UpdateGPSData(content);
    initialize(result);
    return result;
  }

  public class UpdateGPSData extends GpsdataendpointRequest<ch.technotracks.gpsdataendpoint.model.GPSData> {

    private static final String REST_PATH = "gpsdata";

    /**
     * Create a request for the method "updateGPSData".
     *
     * This request holds the parameters needed by the the gpsdataendpoint server.  After setting any
     * optional parameters, call the {@link UpdateGPSData#execute()} method to invoke the remote
     * operation. <p> {@link UpdateGPSData#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link ch.technotracks.gpsdataendpoint.model.GPSData}
     * @since 1.13
     */
    protected UpdateGPSData(ch.technotracks.gpsdataendpoint.model.GPSData content) {
      super(Gpsdataendpoint.this, "PUT", REST_PATH, content, ch.technotracks.gpsdataendpoint.model.GPSData.class);
    }

    @Override
    public UpdateGPSData setAlt(java.lang.String alt) {
      return (UpdateGPSData) super.setAlt(alt);
    }

    @Override
    public UpdateGPSData setFields(java.lang.String fields) {
      return (UpdateGPSData) super.setFields(fields);
    }

    @Override
    public UpdateGPSData setKey(java.lang.String key) {
      return (UpdateGPSData) super.setKey(key);
    }

    @Override
    public UpdateGPSData setOauthToken(java.lang.String oauthToken) {
      return (UpdateGPSData) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateGPSData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateGPSData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateGPSData setQuotaUser(java.lang.String quotaUser) {
      return (UpdateGPSData) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateGPSData setUserIp(java.lang.String userIp) {
      return (UpdateGPSData) super.setUserIp(userIp);
    }

    @Override
    public UpdateGPSData set(String parameterName, Object value) {
      return (UpdateGPSData) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Gpsdataendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Gpsdataendpoint}. */
    @Override
    public Gpsdataendpoint build() {
      return new Gpsdataendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GpsdataendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGpsdataendpointRequestInitializer(
        GpsdataendpointRequestInitializer gpsdataendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(gpsdataendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
