/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-05 at 09:20:49 UTC 
 * Modify at your own risk.
 */

package ch.technotracks.vehicleendpoint;

/**
 * Service definition for Vehicleendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link VehicleendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Vehicleendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the vehicleendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ski-track-group1.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "vehicleendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Vehicleendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Vehicleendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getVehicle".
   *
   * This request holds the parameters needed by the vehicleendpoint server.  After setting any
   * optional parameters, call the {@link GetVehicle#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetVehicle getVehicle(java.lang.Long id) throws java.io.IOException {
    GetVehicle result = new GetVehicle(id);
    initialize(result);
    return result;
  }

  public class GetVehicle extends VehicleendpointRequest<ch.technotracks.vehicleendpoint.model.Vehicle> {

    private static final String REST_PATH = "vehicle/{id}";

    /**
     * Create a request for the method "getVehicle".
     *
     * This request holds the parameters needed by the the vehicleendpoint server.  After setting any
     * optional parameters, call the {@link GetVehicle#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetVehicle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetVehicle(java.lang.Long id) {
      super(Vehicleendpoint.this, "GET", REST_PATH, null, ch.technotracks.vehicleendpoint.model.Vehicle.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetVehicle setAlt(java.lang.String alt) {
      return (GetVehicle) super.setAlt(alt);
    }

    @Override
    public GetVehicle setFields(java.lang.String fields) {
      return (GetVehicle) super.setFields(fields);
    }

    @Override
    public GetVehicle setKey(java.lang.String key) {
      return (GetVehicle) super.setKey(key);
    }

    @Override
    public GetVehicle setOauthToken(java.lang.String oauthToken) {
      return (GetVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public GetVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetVehicle setQuotaUser(java.lang.String quotaUser) {
      return (GetVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetVehicle setUserIp(java.lang.String userIp) {
      return (GetVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetVehicle setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetVehicle set(String parameterName, Object value) {
      return (GetVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertVehicle".
   *
   * This request holds the parameters needed by the vehicleendpoint server.  After setting any
   * optional parameters, call the {@link InsertVehicle#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ch.technotracks.vehicleendpoint.model.Vehicle}
   * @return the request
   */
  public InsertVehicle insertVehicle(ch.technotracks.vehicleendpoint.model.Vehicle content) throws java.io.IOException {
    InsertVehicle result = new InsertVehicle(content);
    initialize(result);
    return result;
  }

  public class InsertVehicle extends VehicleendpointRequest<ch.technotracks.vehicleendpoint.model.Vehicle> {

    private static final String REST_PATH = "vehicle";

    /**
     * Create a request for the method "insertVehicle".
     *
     * This request holds the parameters needed by the the vehicleendpoint server.  After setting any
     * optional parameters, call the {@link InsertVehicle#execute()} method to invoke the remote
     * operation. <p> {@link InsertVehicle#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link ch.technotracks.vehicleendpoint.model.Vehicle}
     * @since 1.13
     */
    protected InsertVehicle(ch.technotracks.vehicleendpoint.model.Vehicle content) {
      super(Vehicleendpoint.this, "POST", REST_PATH, content, ch.technotracks.vehicleendpoint.model.Vehicle.class);
    }

    @Override
    public InsertVehicle setAlt(java.lang.String alt) {
      return (InsertVehicle) super.setAlt(alt);
    }

    @Override
    public InsertVehicle setFields(java.lang.String fields) {
      return (InsertVehicle) super.setFields(fields);
    }

    @Override
    public InsertVehicle setKey(java.lang.String key) {
      return (InsertVehicle) super.setKey(key);
    }

    @Override
    public InsertVehicle setOauthToken(java.lang.String oauthToken) {
      return (InsertVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertVehicle setQuotaUser(java.lang.String quotaUser) {
      return (InsertVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertVehicle setUserIp(java.lang.String userIp) {
      return (InsertVehicle) super.setUserIp(userIp);
    }

    @Override
    public InsertVehicle set(String parameterName, Object value) {
      return (InsertVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listVehicle".
   *
   * This request holds the parameters needed by the vehicleendpoint server.  After setting any
   * optional parameters, call the {@link ListVehicle#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListVehicle listVehicle() throws java.io.IOException {
    ListVehicle result = new ListVehicle();
    initialize(result);
    return result;
  }

  public class ListVehicle extends VehicleendpointRequest<ch.technotracks.vehicleendpoint.model.CollectionResponseVehicle> {

    private static final String REST_PATH = "vehicle";

    /**
     * Create a request for the method "listVehicle".
     *
     * This request holds the parameters needed by the the vehicleendpoint server.  After setting any
     * optional parameters, call the {@link ListVehicle#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListVehicle#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListVehicle() {
      super(Vehicleendpoint.this, "GET", REST_PATH, null, ch.technotracks.vehicleendpoint.model.CollectionResponseVehicle.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListVehicle setAlt(java.lang.String alt) {
      return (ListVehicle) super.setAlt(alt);
    }

    @Override
    public ListVehicle setFields(java.lang.String fields) {
      return (ListVehicle) super.setFields(fields);
    }

    @Override
    public ListVehicle setKey(java.lang.String key) {
      return (ListVehicle) super.setKey(key);
    }

    @Override
    public ListVehicle setOauthToken(java.lang.String oauthToken) {
      return (ListVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public ListVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListVehicle setQuotaUser(java.lang.String quotaUser) {
      return (ListVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListVehicle setUserIp(java.lang.String userIp) {
      return (ListVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListVehicle setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListVehicle setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListVehicle set(String parameterName, Object value) {
      return (ListVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeVehicle".
   *
   * This request holds the parameters needed by the vehicleendpoint server.  After setting any
   * optional parameters, call the {@link RemoveVehicle#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveVehicle removeVehicle(java.lang.Long id) throws java.io.IOException {
    RemoveVehicle result = new RemoveVehicle(id);
    initialize(result);
    return result;
  }

  public class RemoveVehicle extends VehicleendpointRequest<Void> {

    private static final String REST_PATH = "vehicle/{id}";

    /**
     * Create a request for the method "removeVehicle".
     *
     * This request holds the parameters needed by the the vehicleendpoint server.  After setting any
     * optional parameters, call the {@link RemoveVehicle#execute()} method to invoke the remote
     * operation. <p> {@link RemoveVehicle#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveVehicle(java.lang.Long id) {
      super(Vehicleendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveVehicle setAlt(java.lang.String alt) {
      return (RemoveVehicle) super.setAlt(alt);
    }

    @Override
    public RemoveVehicle setFields(java.lang.String fields) {
      return (RemoveVehicle) super.setFields(fields);
    }

    @Override
    public RemoveVehicle setKey(java.lang.String key) {
      return (RemoveVehicle) super.setKey(key);
    }

    @Override
    public RemoveVehicle setOauthToken(java.lang.String oauthToken) {
      return (RemoveVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveVehicle setQuotaUser(java.lang.String quotaUser) {
      return (RemoveVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveVehicle setUserIp(java.lang.String userIp) {
      return (RemoveVehicle) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveVehicle setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveVehicle set(String parameterName, Object value) {
      return (RemoveVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateVehicle".
   *
   * This request holds the parameters needed by the vehicleendpoint server.  After setting any
   * optional parameters, call the {@link UpdateVehicle#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ch.technotracks.vehicleendpoint.model.Vehicle}
   * @return the request
   */
  public UpdateVehicle updateVehicle(ch.technotracks.vehicleendpoint.model.Vehicle content) throws java.io.IOException {
    UpdateVehicle result = new UpdateVehicle(content);
    initialize(result);
    return result;
  }

  public class UpdateVehicle extends VehicleendpointRequest<ch.technotracks.vehicleendpoint.model.Vehicle> {

    private static final String REST_PATH = "vehicle";

    /**
     * Create a request for the method "updateVehicle".
     *
     * This request holds the parameters needed by the the vehicleendpoint server.  After setting any
     * optional parameters, call the {@link UpdateVehicle#execute()} method to invoke the remote
     * operation. <p> {@link UpdateVehicle#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link ch.technotracks.vehicleendpoint.model.Vehicle}
     * @since 1.13
     */
    protected UpdateVehicle(ch.technotracks.vehicleendpoint.model.Vehicle content) {
      super(Vehicleendpoint.this, "PUT", REST_PATH, content, ch.technotracks.vehicleendpoint.model.Vehicle.class);
    }

    @Override
    public UpdateVehicle setAlt(java.lang.String alt) {
      return (UpdateVehicle) super.setAlt(alt);
    }

    @Override
    public UpdateVehicle setFields(java.lang.String fields) {
      return (UpdateVehicle) super.setFields(fields);
    }

    @Override
    public UpdateVehicle setKey(java.lang.String key) {
      return (UpdateVehicle) super.setKey(key);
    }

    @Override
    public UpdateVehicle setOauthToken(java.lang.String oauthToken) {
      return (UpdateVehicle) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateVehicle setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateVehicle) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateVehicle setQuotaUser(java.lang.String quotaUser) {
      return (UpdateVehicle) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateVehicle setUserIp(java.lang.String userIp) {
      return (UpdateVehicle) super.setUserIp(userIp);
    }

    @Override
    public UpdateVehicle set(String parameterName, Object value) {
      return (UpdateVehicle) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Vehicleendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Vehicleendpoint}. */
    @Override
    public Vehicleendpoint build() {
      return new Vehicleendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link VehicleendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setVehicleendpointRequestInitializer(
        VehicleendpointRequestInitializer vehicleendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(vehicleendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
